name: Flutter CI

on:
  push:
    branches: [ feature/correction-node-flutter.yml ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install dependencies
        run: cd frontend-flutter && flutter pub get

      - name: Run tests
        run: cd frontend-flutter && flutter test || echo "No tests found"

      - name: Build APK (Android)
        run: cd frontend-flutter && flutter build apk --release
