name: Node.js CI

on:
  push:
    branches: [ feature/correction-node-flutter.yml ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd back-end && npm install

      - name: Run tests
        run: cd back-end && npm test || echo "No tests found"

      - name: Start server
        run: cd back-end && node server.js
